book/urls.py
from django.urls import path , include

from . import views

app_name = 'book'

urlpatterns = [
    path('',views.books, name='books'),
    path('<int:pk>/',views.detail, name='detail'),
    path('new/',views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('toggle-favorite/<int:book_id>/', views.toggle_favorite, name='toggle_favorite'),

    #Authors part 
    path('authors/',include([
        path('',views.authors, name='authors'),
        path('<int:pk>/',views.author_detail, name='author_detail'),
        path('new/', views.author_new, name='author_new'),
        path('<int:pk>/edit/', views.author_edit, name='author_edit'),
        

    ])),




]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('core.urls')),
    path('',include('book.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path 
from .views import home , signup , login_user , logout_view , soon , termsOfUse

app_name = 'core'

urlpatterns = [
    path('',home,name='index'),

    path('signup/', signup, name='signup'),
    path('login/', login_user, name='login'),
    path('logout/',logout_view,name='logout'),
    path('soon/',soon,name='soon'),
    path('terms/',termsOfUse,name='terms'),

]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):

    email = models.EmailField(unique=True)  
    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from django.contrib.auth.models import User
from .models import CustomUser


class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')
    

core/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login ,logout
from .forms import SignupForm
from django.contrib import messages
#Landing Page
def home(request):
    context = {}
    return render(request,'core/index.html',context)

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            messages.success(request, '! تم تسجيل الدخول بنجاح ')
            success_message = '! تم تسجيل الدخول بنجاح '
            return redirect('book:books')
        else:
            # Handle unsuccessful login
            return render(request, 'core/login.html', {'error_message': 'كلمة المرور أو اسم المستخدم غير صالح'})

    success_message=None

    return render(request, 'core/login.html')


def logout_view(request):

    logout(request)
    messages.success(request, ' ! تم تسجيل الخروج بنجاح')

    return redirect('/')


#404 not found 
def no_page(request,invalid_path):
    return render(request,'core/noPage.html')


# Coming soon view
def soon(request):
    return render(request,'core/comingSoon.html')

# Terms of use view
def termsOfUse(request):
    return render(request,'core/termsOfUse.html')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block meta_description %}Hippo - Plateforme éducative médicale offrant des cours en ligne, documents de référence, et ressources pour étudiants en médecine. Rejoignez-nous pour un apprentissage enrichissant et améliorez vos compétences médicales.{% endblock %}" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" > 
     <script src="https://cdn.tailwindcss.com"></script> 

     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400..700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />    
<title>
        {% block title %}{%endblock title %} | مكتبتي
    </title>
</head>

<body class="bg-[#FFFFFF] text-black min-h-[100vh]"  style="font-family: 'El Messiri', sans-serif;">



<nav class="bg-transparent md:mx-5  mb-20 md:mb-10  z-20 top-0 start-0 border-b  border-gray-600">
  <div class="max-w-screen-xl flex flex-wrap flex-row-reverse items-center justify-between mx-auto p-4">
    <a href="{% url "core:index" %}" class="-m-1.5 drop-shadow-2xl drop-shadow-black">
      <span class="text-3xl font-bold">مكتبتي</span>
      <img class="h-auto w-[60px] md:w-[70px] md:h-auto object-cover" src="" alt=""> 
    </a>
    <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <div class="hidden md:gap-2 md:flex md:flex-row-reverse ">


          {% if not request.user.is_authenticated %}
          <a href="{% url "core:login" %}">
          <button type="button" class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
            دخول
          </button>
          </a>

          <a href="{% url "core:signup" %}">
          <button type="button" class="inline-flex  items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
          تسجيل
          </button>
          </a>
          
        {% else %}
          <a href="#">
          <button type="button" class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
          <i class="fas fa-user"></i>
          </button>
          </a>
          <form action="{% url "core:logout" %}" method="post">
              {% csrf_token %}
                      
              <button type="submit" class="inline-flex items-center rounded-md bg-red-600 px-3 py-3 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600">
                  <i class="fas fa-sign-out-alt"></i>
              </button>
        
          </form>
          
        {% endif %}
      </div>
      

        <button data-collapse-toggle="navbar-sticky" type="button" id="menu-btn" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-sticky" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
      </button>
      
    </div>
    
    <div id="menu-items" class=" items-center justify-between hidden  transition ease duration-1000 w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
      <ul class="bg-gray-900 md:bg-transparent flex items-center justify-center gap-5  flex-col-reverse w-full p-4 md:p-0 mt-4 font-medium border rounded-lg md:space-x-8 rtl:space-x-reverse md:flex-row-reverse md:mt-0 md:border-0 bg-transparent ">

        <form  method="get" action="{% url 'book:books' %}" class="w-[100%] mx-auto">
          <div class="flex flex-row-reverse">
              <select class="w-20 outline-none bg-gray-50 text-gray-700 border border-gray-300  rounded-r-lg">
                <option value="mockups">صنف</option>
                <option value="templates">Templates</option>
                <option value="design">Design</option>
                <option value="logos">Logos</option>
              </select>
              
              <div class="relative w-[500px]">
                  <input type="search" name="query" id="search-dropdown" class="outline-none block px-2.5 py-3 w-full z-20 text-sm text-end text-black bg-gray-50 rounded-l-lg border-s-gray-50 border-s-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 " placeholder=" ... إبحث عن كتاب أو كاتب" required />
                  <button type="submit" class="absolute top-0 start-0 p-2.5 text-sm font-medium h-full text-white bg-blue-700 rounded-l-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 ">
                      <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                      </svg>
                      <span class="sr-only">Search</span>
                  </button>
              </div>
          </div>
      </form>
      
        <div class="md:hidden  flex gap-2">
        

            {% if not request.user.is_authenticated %}
            <a href="#">
            <button type="button" class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
              دخول
            </button>
            </a>

            <a href="#">
            <button type="button" class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
              تسجيل
            </button>
            </a>
            
          {% else %}
            <a href="#">
            <button type="button" class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
            <i class="fas fa-user"></i>
            </button>
            </a>
            <form action="{% url "core:logout" %}" method="post">
                {% csrf_token %}
                        
                <button type="submit" class="inline-flex items-center rounded-md bg-red-600 px-3 py-3 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600">
                    <i class="fas fa-sign-out-alt"></i>
                </button>
          
            </form>
            
          {% endif %}
        
        
        </div>
      </ul>
    </div>
  
  </div>
  
</nav>
<div class="messages">
  {% for message in messages %}
    <div id="message" class="mx-auto my-2 z-10 md:mx-[30%] text-center cursor-pointer bg-green-100 border-t border-b border-green-500 text-green-700 px-4 py-3" role="alert">
      <p class="font-bold">{{ message }}</p>
    </div>
  {% endfor %}
</div>
    {% block content %}
    
    {% endblock content %}
<script>
  const message = document.getElementById('message') ;
  if (message){
    message.onclick = ()=>{message.classList.toggle('hidden');}

  }
  const menuBtn = document.getElementById('menu-btn') ;
  const menuItems = document.getElementById('menu-items') ;
  if (menuBtn){
    menuBtn.onclick = ()=>{
      menuItems.classList.toggle('hidden');
      menuItems.classList.toggle('flex');
    }
  }
  {% block script %}
  
  {% endblock script %}


</script>
</body>
</html>

core/templates/core/comingSoon.html
{% extends "core/base.html" %}

{% block title %}قريباً{% endblock title %}

{% block content %}
<main class="grid  place-items-center  px-6 py-24 sm:py-32 lg:px-8">
  <div class="text-center">
    <p class="text-base font-semibold text-indigo-600">عذراً</p>
    <h1 class="mt-4 text-3xl font-bold tracking-tight  sm:text-5xl">! عن قريب</h1>
    <p class="mt-6 text-base leading-7 ">عذرا، لا يوجد محتوى على هذه الصفحة في الوقت الراهن</p>
    <div class="mt-10 flex items-center justify-center gap-x-6">
      <a href="{% url "core:index" %}" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">الصفحة الرئيسية</a>
      <a href="#" class="text-sm font-semibold ">اتصل بالدعم <span aria-hidden="true">&rarr;</span></a>
    </div>
  </div>
</main>
{% endblock content %}

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Welcome{% endblock title %}

{% block content %}

    <div class="h-[90vh] mx-2 md:mx-auto fixed top-[79px]">
        <section class="h-full rounded-2xl flex items-center justify-center " >
            <div class="content h-full w-full md:w-[60%] col-span-2 flex items-center justify-center gap-5 flex-col">
                <h1 class="text-5xl md:text-6xl font-extrabold text-center"> <span class="text-indigo-700 font-bold">مكتبتي</span> 
                    أكبر منصة 
                    <span class="relative inline-block">
                        <span>🇩🇿</span>
                    </span>
                    للكتب الرقمية 
                </h1>
                <p class="text-sm md:text-lg text-gray-700 text-center leading-relaxed mt-5 ">
                    مكتبتي هي منصة إلكترونية متخصصة في الكتب الرقمية (الكتب الإلكترونية)،
                    تتيح للمستخدمين الوصول إلى مجموعة واسعة من الكتب في مختلف المجالات. 
                    من خلال "مكتبتي"،
                    يمكن للمستخدمين استعراض، قراءة، وتحميل الكتب بسهولة من أي مكان وفي أي وقت. 
                    تهدف المنصة إلى تسهيل الوصول إلى المعرفة وتشجيع القراءة عبر الوسائط الرقمية.
                </p>
                <div class="flex items-center justify-center gap-2">
                    <a href="{% url "book:authors" %}" class="py-4 px-10 rounded-3xl bg-indigo-700 hover:bg-indigo-600  text-white"> البحث عن الكتاب</a>
                    
                    <a href="{% url "book:books" %}" class="py-4 px-10 rounded-3xl bg-indigo-700 hover:bg-indigo-600  text-white">ابدأ القراءة</a>

                </div>
            </div>
        </section>
    </div>
{% endblock content %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="flex  flex-col justify-center px-6 py-12 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
  {% if request.user.is_authenticated %}
    <h2 class="text-center text-3xl font-bold leading-9 tracking-tight ">لقد قمت بتسجيل الدخول بالفعل.</h2> 
    <div class="mt-10 flex items-center justify-center gap-x-6">
      <a href="{% url "core:index" %}" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Accueil</a>
        <form action="{% url 'core:logout' %}" method="post">
            {% csrf_token %}
                    
            <button type="submit" class="inline-flex items-center rounded-md bg-red-600 px-3 py-3 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600">
            <i class="fa-solid fa-right-from-bracket"></i>
            </button>
       
        </form>
    </div>

  {%else%}    
    <h2 class="text-center text-3xl font-bold leading-9 tracking-tight ">تسجيل الدخول إلى حسابك</h2>
    {% comment %} showing errors {% endcomment %}
    {% if error_message %}
        <div class="mt-2 bg-red-400 text-white p-3 rounded-xl border-2 border-rose-500 ">
            
                {{ error_message }}
            
  
        </div>
    {% endif %}
  </div>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-6" action="{% url "core:login" %}" method="post">
        {% csrf_token %}
      <div>
        <label for="username" class="block text-sm text-end font-medium leading-6 ">اسم المستخدم</label>
        <div class="mt-2">
          <input id="username" name="username" type="text" autocomplete="username" required class="text-white text-end  block w-full rounded-md border py-1.5 px-2   shadow outline-none placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        </div>
      </div>
      <div>



      <div>
        <div class="flex flex-row-reverse items-center justify-between">
          <label for="password" class="block text-sm font-medium leading-6  ">كلمة المرور</label>
          <div class="text-sm">
            <a href="#" class="font-semibold text-indigo-600 hover:text-indigo-500">هل نسيت كلمة المرور؟</a>
          </div>
        </div>
        <div class="mt-2">
          <input id="password" name="password" type="password" required class="text-white text-end  block w-full rounded-md border-0 py-1.5 px-2   shadow outline-none placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        </div>
      </div>
      <br>


      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">تسجيل الدخول</button>
      </div>
    </form>

    <p class="mt-10 text-center text-sm text-gray-500">
      لست عضوا؟
      <a href="{% url "core:signup" %}" class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500">سجل نفسك</a>
    </p>
{%endif%}
  </div>
</div>


{% endblock %}

core/templates/core/noPage.html
{% extends "core/base.html" %}

{% block title %}Not found{% endblock title %}

{% block content %}
<main class="grid min-h-full place-items-center  px-6 py-24 sm:py-32 lg:px-8">
  <div class="text-center">
    <p class="text-base font-semibold text-indigo-600">404</p>
    <h1 class="mt-4 text-3xl font-bold tracking-tight  sm:text-5xl">Page not found</h1>
    <p class="mt-6 text-base leading-7 ">Sorry, we couldn’t find the page you’re looking for.</p>
    <div class="mt-10 flex items-center justify-center gap-x-6">
      <a href="{% url "core:index" %}" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Go back home</a>
      <a href="#" class="text-sm font-semibold ">Contact support <span aria-hidden="true">&rarr;</span></a>
    </div>
  </div>
</main>
{% endblock content %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}

<div class="flex  flex-col justify-center px-6 py-12 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">    
    <h2 class="text-center text-3xl font-bold leading-9 tracking-tight ">مرحبا بكم في مجتمعنا</h2>
    {% comment %} showing errors {% endcomment %}
    {% if form.errors or form.non_field_errors %}
        <div class="mt-2 bg-red-400 text-white p-3 rounded-xl border-2 border-rose-500 ">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
  
            {{ form.non_field_errors }}
        </div>
    {% endif %}
  </div>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-6" action="{% url "core:signup" %}" method="post">
        {% csrf_token %}
        <div class="flex justify-between flex-col gap-2">
          <div>
            <label for="username" class="block  text-end text-sm font-medium leading-6 ">اسم المستخدم</label>
            <div class="mt-2">
              <input id="username" name="username" type="text" autocomplete="username" required class="text-white text-end bg-[#31363F] block w-full rounded-md border-0 py-1.5 px-2 outline-none shadow-sm  placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            </div>
          </div>
          <div>
            <label for="email" class="block text-end text-sm font-medium leading-6 ">بريد إلكتروني</label>
            <div class="mt-2">
            <input id="email" name="email" type="email" autocomplete="email" required class="text-white bg-[#31363F] block w-full rounded-md border-0 py-1.5 px-2 outline-none shadow-sm  placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            </div>
          </div>
        </div>
        <div class="flex flex-row-reverse justify-between gap-2">
          <div>
            <label for="password" class="block text-end text-sm font-medium leading-6 ">كلمة المرور</label>
            <div class="mt-2">
              <input id="password1" name="password1" type="password" autocomplete="password" required class=" text-white bg-[#31363F] block w-full rounded-md border-0 py-1.5 px-2 outline-none shadow-sm  placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            </div>
          </div>
          <div>
            <label for="password2" class="block text-end text-sm font-medium leading-6 ">كرر كلمة المرور</label>
            <div class="mt-2">
              <input id="password2" name="password2" type="password"  required class="text-white bg-[#31363F] block w-full rounded-md border-0 py-1.5 px-2 outline-none shadow-sm  placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            </div>
          </div>
        </div>  
        



      <label class="flex flex-row-reverse cursor-pointer items-center justify-between p-1 text-slate-400">
      <div> هل تقبل <a href="{% url "core:terms"%}" class="text-indigo-500">شروط الاستخدام</a> </div>
      <div class="relative inline-block">
        <input class="peer h-6 w-12 cursor-pointer appearance-none rounded-full border border-gray-300 bg-gary-400 checked:border-green-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-900 focus-visible:ring-offset-2" type="checkbox" required>
        <span class="pointer-events-none absolute left-1 top-1 block h-4 w-4 rounded-full bg-slate-600 transition-all duration-200 peer-checked:left-7 peer-checked:bg-green-300"></span>
      </div>
    </label>
      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 py-1.5 px-3 outline-nonetext-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">سجل الآن</button>
      </div>
    </form>

    <p class="mt-10 text-center text-sm text-gray-500">
      هل أنت عضو بالفعل؟
      <a href="{% url "core:login" %}" class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500">تسجيل الدخول</a>
    </p>

  </div>
</div>
{% endblock %}

core/templates/core/soonComponent.html
<main class="col-span-6 w-full my-20 grid  place-items-center  px-6  md:px-8">
  <div class="text-center">
    <p class="text-base font-semibold text-indigo-600">عذراً</p>
    <h1 class="mt-4 text-3xl font-bold tracking-tight  sm:text-5xl">! عن قريب</h1>
    <p class="mt-6 text-base leading-7 ">عذرا، لا يوجد كتب لهذا التصنيف في الوقت الراهن</p>
    <div class="mt-10 flex items-center justify-center gap-x-6">
      <a href="{% url "book:books" %}" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"> العودة</a>
      <a href="#" class="text-sm font-semibold ">اتصل بالدعم <span aria-hidden="true">&rarr;</span></a>
    </div>
  </div>
</main>