book/urls.py
from django.urls import path , include

from . import views

app_name = 'book'

urlpatterns = [
    path('',views.books, name='books'),
    path('<int:pk>/',views.detail, name='detail'),
    path('new/',views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('toggle-favorite/<int:book_id>/', views.toggle_favorite, name='toggle_favorite'),

    #Authors part 
    path('authors/',include([
        path('',views.authors, name='authors'),
        path('<int:pk>/',views.author_detail, name='author_detail'),
        path('new/', views.author_new, name='author_new'),
        path('<int:pk>/edit/', views.author_edit, name='author_edit'),
        

    ])),




]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('core.urls')),
    path('',include('book.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path 
from .views import home , signup , login_user , logout_view , soon , termsOfUse

app_name = 'core'

urlpatterns = [
    path('',home,name='index'),

    path('signup/', signup, name='signup'),
    path('login/', login_user, name='login'),
    path('logout/',logout_view,name='logout'),
    path('soon/',soon,name='soon'),
    path('terms/',termsOfUse,name='terms'),

]

book/models.py
from django.db import models
from core.models import CustomUser as User
class Category(models.Model):
    name = models.CharField(max_length=255 ,  unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class Book(models.Model):
    category = models.ForeignKey(Category, related_name='books', on_delete=models.CASCADE , blank=True , null=True)
    subject = models.CharField(max_length=255 , blank=True , null = True ) 
    name = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    pages = models.IntegerField(blank=True , null=True)
    link= models.URLField()
    image = models.ImageField(upload_to='book_covers',  blank=True, null=True) 
    image_url = models.URLField(null=True , blank=True)
    posted_at = models.DateTimeField(auto_now_add=True)
    

    # Rating fields  
    average_rating = models.FloatField(default=0.0)
    review_count = models.IntegerField(default=0)
    
    def total_favorites(self):
        return Favorite.objects.filter(book=self).count()
    
    def __str__(self):
        return self.name

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = ('user', 'book')  # Prevent duplicates
        
class Review(models.Model):
    book = models.ForeignKey(Book, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    rating = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)])  # Rating from 1 to 5
    posted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.book.name}'


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Update the book's average rating and review count
        reviews = self.book.reviews.all()
        total_reviews = reviews.count()
        total_rating = sum([review.rating for review in reviews])
        
        self.book.average_rating = total_rating / total_reviews
        self.book.review_count = total_reviews
        self.book.save()



class Author_Details (models.Model):
    name = models.CharField(max_length=250 , null= False , blank= False)
    bio = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='author_pics', blank=True, null=True) 
    books = models.ManyToManyField( Book, verbose_name="author_book" , blank=True )

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Authors'
    
    def __str__(self):
        return self.name

book/forms.py
from django import forms

from .models import Book , Review , Author_Details


class NewBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('category', 'name', 'author', 'description', 'image',)


class EditBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('name','author' , 'description', 'image')


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'rating']
        widgets = {
            'rating': forms.RadioSelect(choices=[(i, f'{i} Stars') for i in range(1, 6)], attrs={
                'class': 'flex flex-row-reverse gap-2',
            }),
            'comment': forms.Textarea(attrs={
                'class': 'form-textarea text-end mt-2 w-[95%] md:w-[50%] border-1 p-6 shadow rounded border-gray-300',
                'placeholder': ' ... اكتب رأيك هنا',
                'rows': 4,
            }),
        }


class NewAuthorForm(forms.ModelForm):
    class Meta:
        model = Author_Details
        fields = ('name', 'bio','image')


class EditAuthorForm(forms.ModelForm):
    class Meta:
        model = Author_Details
        fields = ('name','bio','image')

book/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.db.models import Count

from .forms import NewBookForm, EditBookForm , ReviewForm , NewAuthorForm , EditAuthorForm
from .models import Category, Book , Favorite , Review , Author_Details

from django.core.paginator import Paginator
from django.http import JsonResponse

def books(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    page = request.GET.get('page', 1)  # Get the current page number
    books = Book.objects.order_by('?')
    categories = Category.objects.annotate(book_count=Count('books'))
    all_books_count = Book.objects.all().count()

    if category_id:
        books = books.filter(category_id=category_id)

    if query:
        books = books.filter(Q(name__icontains=query) | Q(description__icontains=query))

    # Paginate the books queryset
    paginator = Paginator(books, 18)  
    books = paginator.get_page(page)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        books_data = [
            {
                'id': book.id,
                'name': book.name,
                'author': book.author,
                'image_url': book.image.url if book.image else book.image_url,
                'average_rating': book.average_rating
            }
            for book in books
        ]
        return JsonResponse({'books': books_data, 'has_next': books.has_next()})

    favorites = []
    if request.user.is_authenticated:
        favorite_books = Favorite.objects.filter(user=request.user).values_list('book_id', flat=True)
        favorites = list(favorite_books)

    return render(request, 'book/books.html', {
        'books': books,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
        'favorites': favorites,
        'all_books_count': all_books_count,
    })


def detail(request, pk):
    book = get_object_or_404(Book, pk=pk)
    related_books = Book.objects.filter(category=book.category).exclude(pk=pk)[0:3]
    reviews = book.reviews.all()
    favorites = []

    if request.user.is_authenticated:
        favorite_books = Favorite.objects.filter(user=request.user).values_list('book_id', flat=True)
        favorites = list(favorite_books)

    user_review = None
    if request.user.is_authenticated:
        user_review = Review.objects.filter(book=book, user=request.user).first()

    if request.method == 'POST' and not user_review:
        if request.user.is_authenticated:
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.book = book
                review.user = request.user
                review.save()
                return redirect('book:detail', pk=book.id)
        else:
            # Redirect to login if not authenticated
            return redirect('login')
    else:
        form = ReviewForm()

    return render(request, 'book/detail.html', {
        'book': book,
        'related_books': related_books , 
        'favorites' : favorites ,
        'reviews': reviews ,
        'form': form ,
        'user_review': user_review,
    })

@login_required

def new(request):
    if request.method == 'POST':
        form = NewBookForm(request.POST, request.FILES)

        if form.is_valid():
            book = form.save(commit=False)
            book.save()

            return redirect('book:detail', pk=book.id)
    else:
        form = NewBookForm()

    return render(request, 'book/form.html', {
        'form': form,
        'title': 'New book',
    })

@login_required

def edit(request, pk):
    book = get_object_or_404(Book, pk=pk)

    if request.method == 'POST':
        form = EditBookForm(request.POST, request.FILES, instance=book)

        if form.is_valid():
            form.save()

            return redirect('book:detail', pk=book.id)
    else:
        form = EditBookForm(instance=book)

    return render(request, 'book/form.html', {
        'form': form,
        'title': 'Edit book',
    })

@login_required
def delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    book.delete()

    return redirect('/')

@login_required
def toggle_favorite(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    user = request.user
    
    # Toggle the favorite status
    favorite, created = Favorite.objects.get_or_create(user=user, book=book)
    
    if not created:
        favorite.delete()
        return JsonResponse({'favorite': False})  # Return status for frontend
    
    return JsonResponse({'favorite': True})


#! Authors Part 

def authors(request):
    query = request.GET.get('query', '')
    authors = Author_Details.objects.order_by('?')

    if query:
        authors = authors.filter(Q(name__icontains=query) | Q(description__icontains=query))



    return render(request , "book/authors.html" , {
        'authors': authors ,
        'query': query,
    })


def author_detail(request, pk):
    author = get_object_or_404(Author_Details, pk=pk)

    return render(request, 'book/author_detail.html', {
        'author': author,
    })

@login_required

def author_new(request):
    if request.method == 'POST':
        form = NewAuthorForm(request.POST, request.FILES)

        if form.is_valid():
            author = form.save(commit=False)
            author.save()

            return redirect('author:detail', pk=author.id)
    else:
        form = NewAuthorForm()

    return render(request, 'book/author_form.html', {
        'form': form,
        'title': 'New Author',
    })


@login_required

def author_edit(request, pk):
    author = get_object_or_404(Author_Details, pk=pk)

    if request.method == 'POST':
        form = EditAuthorForm(request.POST, request.FILES, instance=author)

        if form.is_valid():
            form.save()

            return redirect('book:author_detail', pk=author.id)
    else:
        form = EditAuthorForm(instance=author)

    return render(request, 'book/author_form.html', {
        'form': form,
        'title': 'Edit author',
    })

book/templates/book/author_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ author.name }}{% endblock %}

{% block content %}

<div class="mx-2 md:mx-10 ">
<div class="mx-4 flex flex-wrap flex-row-reverse  md:text-md gap-2 mt-2 mb-6 ">
    <p class="hover:underline">
        <a href="{% url "core:index" %}">
            الصفحة الرئيسية
        </a>
    </p>
    <i class="fas fa-angle-left"></i>
    <p class="hover:underline">
        <a href="{% url "book:authors" %}">
            جميع الكتاب
        </a>
    </p>
    <i class="fas fa-angle-left"></i>
    <p>
        <a>
            {{author.name}}
        </a>
    </p>

</div>
<div class="flex flex-col-reverse items-center justify-center mt-5 md:mt-auto  md:grid md:grid-cols-5 gap-6">



    <div class="relative w-full md:w-auto  md:col-span-4 p-6 bg-gray-50 rounded-xl flex flex-col items-end">

        <h1 class="mb-6 text-3xl">{{ author.name }}</h1>

        <p class="inline-flex flex-row-reverse gap-3 text-gray-500">
            <strong> : الكاتب</strong>
            {{ author.name }}

        </p>

        {% if author.bio %}
            <p class="inline-flex flex-row-reverse  w-full text-end text-gray-500">
                <strong class="text-gray-500"> : الوصف</strong>
                <br>
                <p class="text-end whitespace-pre-line">
                    {{ author.bio }}

                </p>
            </p>
        {% endif %}



    </div>


    <div class="flex items-center justify-center md:block w-full md:col-span-1">
        <img src="{{ author.image.url }}" class="rounded-xl  w-[80%] md:w-full">
    </div>
</div>



</div>



</div>

{% endblock %}

book/templates/book/authors.html
{% extends 'core/base.html' %}

{% block title %}كتب{% endblock %}

{% block content %}
    <meta name="csrf-token" content="{{ csrf_token }}">
<div class="md:mx-10">
    <h1 class="text-center mb-6 text-4xl font-semibold">أشهر المؤلفين والكتاب</h1>
    <div class="flex flex-row-reverse gap-2 md:mt-2 mb-6 mx-5 ">
                <p class="hover:underline">
                    <a href="{% url "core:index" %}">
                        الصفحة الرئيسية
                    </a>
                </p>
                <i class="fas fa-angle-left"></i>
                <p class="hover:underline">
                    <a href="{% url "book:books" %}">
                        جميع الكتاب
                    </a>
                </p>
    </div>
    <div class=" pb-6 grid gap-4">
        
        <div>
            <div class="mx-5 md:mx-auto grid grid-cols-2 md:grid-cols-8 place-items-start gap-2">
            {% if authors %}
                
                {% for author in authors %}
                    <div class="hover:shadow-2 border rounded-xl border-gray-200 w-full h-full relative">

                        <a href="{% url "book:author_detail" author.id %}" class="w-full ">
                            <div class=" w-full h-[70%]">
                                {% if author.image %}
                                <img src="{{ author.image.url }}" class="rounded-t-xl object-cover w-full h-full">
                                {% endif %}
                            </div>
    
                            <div class="h-[30%] p-6 px-2 bg-white rounded-b-xl">
                                <h2 class="text-end text-xl text-black">{{ author.name }}</h2>
                                <div class="flex items-center mb-5">

                                </div>
                            </div>
                            
                        </a>
                    </div>
                {% endfor %}

                {% else %}
                    {% include "core/soonComponent.html" %}
                {% endif %}

            </div>
        </div>



    </div>

</div>

    
{% endblock %}

book/templates/book/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ book.name }}{% endblock %}

{% block content %}

<div class="mx-2 md:mx-10 ">
<div class="mx-4 flex flex-wrap flex-row-reverse  md:text-md gap-2 mt-2 mb-6 ">
    <p class="hover:underline">
        <a href="{% url "core:index" %}">
            الصفحة الرئيسية
        </a>
    </p>
    <i class="fas fa-angle-left"></i>
    <p class="hover:underline">
        <a href="{% url "book:books" %}">
            جميع الكتب
        </a>
    </p>
    <i class="fas fa-angle-left"></i>
    <p class="hover:underline">
        <a href="{% url 'book:books' %}?category={{ book.category.id }}">
            {{book.category}}
        </a>
    </p>
    <i class="fas fa-angle-left"></i>
    <p class="hover:underline">
        <a href="#">
            {{book.name}}
        </a>
    </p>
</div>
<div class="flex flex-col-reverse items-center justify-center mt-5 md:mt-auto  md:grid md:grid-cols-5 gap-6">



    <div class="relative w-full md:w-auto md:self-start  md:col-span-4 p-6 bg-gray-50 rounded-xl flex flex-col items-end">
        {% if request.user.is_authenticated %}
        <div class="flex flex-row gap-2 absolute -top-10 md:top-5 left-[50%] -translate-x-[50%] md:-translate-x-0 md:left-5 ">

            <div class="h-10 w-10 flex items-center justify-center gap-2 cursor-pointer z-10 rounded-3xl bg-white   text-indigo-700 hover:text-white hover:bg-indigo-700">
                    <button class="favorite-btn flex items-center justify-center" data-book-id="{{ book.id }}">
                        <i class="favorite-icon {% if book.id in favorites %}fas fa-heart{% else %}far fa-heart{% endif %}"></i>
                    </button>
                    
            </div>
            <div class=" flex items-center justify-center gap-2 cursor-pointer z-10 rounded-xl bg-white   text-indigo-700 hover:text-white hover:bg-indigo-700">
                <button class="flex items-center flex-row-reverse gap-2 justify-center py-2 px-3" >
                    <i class="fas fa-share-alt"></i>
                    
                       النشر 
                    
                </button>
                
            </div>
            <div class=" flex items-center justify-center gap-2 cursor-pointer z-10 rounded-xl bg-white   text-indigo-700 hover:text-white hover:bg-indigo-700">
                <button class="flex items-center flex-row-reverse gap-2 justify-center py-2 px-3" >
                    <i class="far fa-star"></i>
                    
                       تقييم 
                    
                </button>
                
            </div>
        </div>                        

        {% endif %}
        <h1 class="mb-6 text-3xl">{{ book.name }}</h1>
        <div class="flex items-center justify-center flex-wrap  flex-row-reverse gap-2 md:gap-[25px]">
            <div class="flex items-center justify-center md:mt-2.5 md:mb-5">

                {% with 5 as total_stars %}
                    <div class="flex items-center space-x-1 rtl:space-x-reverse">
                        {% for i in "12345" %}
                            {% if forloop.counter <= book.average_rating %}
                                <svg class="w-4 h-4 text-indigo-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                            {% else %}
                                <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                            {% endif %}
                        {% endfor %}
                        <span class="flex items-center justify-center mt-1">
                            {{ book.average_rating }}
                        </span>
                    </div>
                {% endwith %}
            

            </div>

            <div class="flex items-center flex-row-reverse justify-center gap-2">
                <i class="far fa-comments text-indigo-700"></i>
                <p>{{ book.review_count }}</p>
                <p>تعليق</p>

            </div>
            <div class="flex items-center flex-row-reverse justify-center gap-2">
                <i class="far fa-heart text-indigo-700"></i>
                <p>{{ book.total_favorites }}</p>
                <p>مفضلة</p>

            </div>
            {% if book.pages %}
                <div class="flex items-center flex-row-reverse justify-center gap-2">
                    <i class="far fa-file text-indigo-700"></i>
                    <p>{{ book.pages }}</p>
                    <p>صفحة</p>

                </div>
            {% endif %}
        </div>
        <p class="inline-flex flex-row-reverse gap-3 text-gray-500">
            <strong> : الكاتب</strong>
            {{ book.author }}
            
            <strong> : تاريخ النشر </strong>
            {{ book.posted_at|date:"Y M d" }}
        </p>

        {% if book.description %}
            <p class="inline-flex flex-row-reverse  w-full text-end text-gray-500">
                <strong class="text-gray-500"> : الوصف</strong>
                <br>
                <p class="text-end whitespace-pre-line">
                    {{ book.description }}

                </p>
            </p>
        {% endif %}

        <div class="mt-6 p-6  rounded-xl">
            
            {% if request.user.is_staff %}

                <a href="{% url 'book:delete' book.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-700 hover:bg-red-600 text-white rounded-xl">حذف</a>
                <a href="{% url 'book:edit' book.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-indigo-700 hover:bg-indigo-600 text-white rounded-xl">تعديل</a>
            
            {% endif %}

            <a href="{{book.link}}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-indigo-700 hover:bg-indigo-600 text-white rounded-xl">تحميل الكتاب</a>

            </div>

    </div>


    <div class="flex items-center justify-center md:self-start md:block w-full md:col-span-1">
        {% if book.image %}
        <img src="{{ book.image.url }}" class="rounded-xl  w-[80%] md:w-full">
        
        {% else %}
        <img src="{{ book.image_url }}" class="rounded-xl  w-[80%] md:w-full">
        
        {% endif %}
    </div>
</div>

    <div class="mt-6 px-6 py-12 rounded-xl bg-gray-50">

        <h2 class="mb-12 text-2xl text-center">تقييمات</h2>

        <ul class="w-full text-end flex flex-col items-end">
            {% for review in reviews %}
            <li class="border-2 p-6 w-full md:w-[70%] rounded-xl flex flex-col gap-1 mb-5 ">
                <span class="inline-flex flex-row-reverse gap-2">

                    <strong>:{{ review.user.username }}</strong> 

                    <p class="flex gap-1 justify-end">
                        {{ review.rating }} 
                        <svg class="w-4 h-4 text-indigo-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                            <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                        </svg>
                    </p>

                </span>

                <em class="text-end mx-10">{{ review.posted_at }} تم النشر في </em>
                <p class="text-end mx-10">
                    {{ review.comment }}
                </p>
            </li>
            {% empty %}
            <li>لا توجد تعليقات حتى الآن</li>
            {% endfor %}
        </ul>
        
        {% if user.is_authenticated %}
            {% if user_review %}
                <p class="text-end mt-5">لقد قمت بالفعل بتقديم تقييم لهذا الكتاب.</p>
            {% else %}
                <form method="POST" class="flex flex-col gap-2 mt-5 items-end justify-center">
                    {% csrf_token %}
                    <label for="{{ form.rating.id_for_label }}" class="block text-gray-700 font-bold">
                         : تقييم
                    </label>
                    {{ form.rating }}
                    <label for="{{ form.comment.id_for_label }}" class="block text-gray-700 font-bold">
                        : تعليق
                    </label>
                    {{ form.comment }}
                    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">تقييم الأن</button>
                </form>
            {% endif %}
        {% else %}
            <p class="text-end mt-5">تحتاج إلى <a href="{% url 'core:login' %}" class="text-indigo-700 hover:underline">تسجيل الدخول</a> لتقديم تقييم</p>
        {% endif %}
        
    </div>

</div>

<div class="md:mx-[5%] mt-6 md:px-6 py-12 rounded-xl">

    <h2 class="mb-12 text-2xl text-center">الكتب ذات الصلة</h2>

    <div class="flex flex-col items-center justify-center md:flex-row-reverse gap-3">

        {% for book in related_books %}

            <div class="w-full max-w-sm hover:shadow shadow-gray-900  grid grid-cols-3 py-2 px-4   rounded-lg bg-gray-50 ">
                
                <div class="flex flex-col  gap-2 col-span-2 px-5 pb-5">
                    <a href="{% url 'book:detail' book.id %}">
                        <h5 class="text-xl text-end font-semibold tracking-tight ">{{ book.name }}</h5>
                    </a>
                    {% with 5 as total_stars %}
                    <div class="flex items-center justify-end space-x-1 rtl:space-x-reverse">
                        {% for i in "12345" %}
                            {% if forloop.counter <= book.average_rating %}
                                <svg class="w-4 h-4 text-indigo-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                            {% else %}
                                <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endwith %}
                    <p class="inline-flex flex-row-reverse gap-3 text-gray-500">
                        <strong> : الكاتب</strong>
                        {{ book.author }}
                        

                    </p>
                </div>
                <a href="{% url 'book:detail' book.id %}">
                    {% if book.image %}
                    <img class=" rounded-lg object-contain" src="{{ book.image.url }}" alt="{{book.name}}" />
                    
                    {% else %}
                    <img class=" rounded-lg object-contain" src="{{ book.image_url }}" alt="{{book.name}}" />
                    {% endif %}
                </a>
            </div>

        {% endfor %}

    </div>

</div>

</div>

<script>
    document.querySelectorAll('.favorite-btn').forEach(button => {
        button.addEventListener('click', function() {
            const bookId = this.getAttribute('data-book-id');
            const icon = this.querySelector('.favorite-icon');

            fetch(`/toggle-favorite/${bookId}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json',
                },
            })
            .then(response => response.json())
            .then(data => {
                if (data.favorite) {
                    icon.classList.remove('far', 'fa-heart');
                    icon.classList.add('fas', 'fa-heart');
                } else {
                    icon.classList.remove('fas', 'fa-heart');
                    icon.classList.add('far', 'fa-heart');
                }
            })
            .catch(error => console.error('Error:', error));
        });
    });
</script>
{% endblock %}